---
name: Super-Linter Code Quality checkpoint

on:
  # push:
  #   branches:
  #     main
  
  # pull_request:
  #   branches:
  #     main

  workflow_dispatch:

permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: Install Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          VALIDATE_JSCPD: false
          VALIDATE_HTML: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...