---
name: Movie Watch List Tracker

on: push

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: Install Super-Linter
        uses: github/super-linter@v4
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: '\.(html|js|css)$'

      - name: Run Super-Linter
        run: super-linter --fail-on-errors --format summary
...