---
name: Movie Watch List Tracker

on: push

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: Install Super-Linter
        uses: github/super-linter@v4

      - name: Run Super-Linter
        run: super-linter --fail-on-errors --format summary
...