---
name: Movie Watch List Tracker

on: push

jobs:
  lint:
    name: Lint the Codebase
    runs-on: ubuntu-latest

    steps:
      -name: checkout the repository
       uses: actions/checkout@v3

     -name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
...
