---
name: Movie Watch List Tracker

on:
  push:
    branches:
      main
  
  pull_request:
    branches:
      main

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: Install Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: 'dict|\.(html|js|css)$'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...