---
name: Build and Push the Docker image

on:
  push:
    branches:
        main

  pull_request:
    branches:
        main

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mralham/movie_watch_list:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: /app/Dockerfile
          pull: true
...
